executable=/project/atlas/users/mfernand/sbi_madminer_code/ggF/condor/mfernand/condorsub/ggF_generation_809384.sh
JobBatchName=ggF_generation_809384
+JobCategory="medium"
+UseOS="el9"
+MaxWallTime=
request_cpus=4
request_memory=16000
log = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_809384_809384.condorlog
output = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_809384_809384.log
error = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_809384_809384.stderr
queue
