executable=/project/atlas/users/mfernand/sbi_madminer_code/ggF/condor/mfernand/condorsub/ggF_generation_813153.sh
JobBatchName=ggF_generation_813153
+JobCategory="medium"
+UseOS="el9"
+MaxWallTime=
request_cpus=4
request_memory=16000
log = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_813153_813153.condorlog
output = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_813153_813153.log
error = /project/atlas/users/mfernand/sbi_madminer_code/ggF/ggF_generation_813153_813153.stderr
queue
